# Generated by Django 5.2 on 2025-04-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
